CREATE SCHEMA TESTING

show warehouses

create or replace TABLE TESTING.TEST_METADATA_TABLE (
	SCHEMA_NAME VARCHAR(16777216),
	TABLE_NAME VARCHAR(16777216),
	COLUMN_NAME VARCHAR(16777216),
	TEST_TYPE VARCHAR(16777216),
	TEST_CONFIG VARCHAR(16777216)
);

INSERT INTO TESTING.TEST_METADATA_TABLE (
    SCHEMA_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    TEST_TYPE,
    TEST_CONFIG
)
VALUES (
    'STG',
    'stg_country',
    NULL,
    'source_to_target_range',
    '{
        "source_table": "RAW.COUNTRY",
        "source_key_list": ["COUNTRY_ID", "CITY_ID"],
        "source_timestamp": "lastupdateddate",
        "auditlog_table": "lcf.auditlog",
        "target_key": "country_city_key"
    }'
);


CREATE SCHEMA lcf

create or replace TABLE lcf.auditlog (
	AUDITLOGID NUMBER(38,0) NOT NULL,
	TABLENAME VARCHAR(256),
	STARTDATE TIMESTAMP_NTZ(9),
	ENDDATE TIMESTAMP_NTZ(9),
	LOADSTARTTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LOADENDTIME TIMESTAMP_NTZ(9),
	TOTALRECORDS NUMBER(38,0),
	RECORDSINSERTED NUMBER(38,0),
	RECORDSUPDATED NUMBER(38,0),
	RECORDSDELETED NUMBER(38,0),
	STATUS VARCHAR(50),
	ERROR VARCHAR(2000),
	LOADEDBY VARCHAR(256) DEFAULT CURRENT_USER(),
	primary key (AUDITLOGID)
);

SELECT * FROM lcf.highwatermark

create or replace TABLE lcf.highwatermark (
	TABLE_NAME VARCHAR(16777216),
	START_DATE TIMESTAMP_NTZ(9),
	END_DATE TIMESTAMP_NTZ(9)
);

select * from lcf.auditlog


Select * from jaffle_shop.staging.test_metadata_table

INSERT INTO TASTY_BYTES_DBT_DB.TESTING.TEST_METADATA_TABLE 
VALUES (
  'STAGING',                                         -- LAYER / CONTEXT
  'STG_ORDERS',                                     -- MODEL NAME
  NULL,                                              -- ADDITIONAL INFO (if any)
  'NO_DUPLICATES_IN_STG',                            -- TEST TYPE / TEST NAME
  '{"test_name": "no_duplicates_in_stg",
    "description": "Verify no duplicate records are introduced after staging transformations.",
    "columns": ["ORDER_ID", "CUSTOMER_ID"],
    "model": "\"{{ ref(\'stg_orders\') }}\""
  }'
);



CREATE OR REPLACE TABLE lcf.AUDITLOG_NEW AS
SELECT 
    SEQ8() + 1 AS AUDITLOGID,  -- SEQ8() auto-generates incremental IDs
    TABLENAME,
    STARTDATE,
    ENDDATE,
    LOADSTARTTIME,
    LOADENDTIME,
    TOTALRECORDS,
    RECORDSINSERTED,
    RECORDSUPDATED,
    RECORDSDELETED,
    STATUS,
    ERROR,
    LOADEDBY
FROM AUDITLOG order by LOADSTARTTIME;

ALTER TABLE lcf.AUDITLOG RENAME TO lcf.AUDITLOG_OLD;
ALTER TABLE lcf.AUDITLOG_NEW RENAME TO lcf.AUDITLOG;

CREATE OR REPLACE TABLE lcf.AUDITLOG AS
SELECT * FROM lcf.AUDITLOG;

CREATE OR REPLACE TABLE lcf.AUDITLOG (
    AUDITLOGID NUMBER(38,0) IDENTITY(1,1) PRIMARY KEY,
    TABLENAME VARCHAR(256),
    STARTDATE TIMESTAMP_NTZ(9),
    ENDDATE TIMESTAMP_NTZ(9),
    LOADSTARTTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    LOADENDTIME TIMESTAMP_NTZ(9),
    TOTALRECORDS NUMBER(38,0),
    RECORDSINSERTED NUMBER(38,0),
    RECORDSUPDATED NUMBER(38,0),
    RECORDSDELETED NUMBER(38,0),
    STATUS VARCHAR(50),
    ERROR VARCHAR(2000),
    LOADEDBY VARCHAR(256) DEFAULT CURRENT_USER()
);

INSERT INTO lcf.AUDITLOG (
    TABLENAME,
    STARTDATE,
    ENDDATE,
    LOADSTARTTIME,
    LOADENDTIME,
    TOTALRECORDS,
    RECORDSINSERTED,
    RECORDSUPDATED,
    RECORDSDELETED,
    STATUS,
    ERROR,
    LOADEDBY
)
SELECT 
    TABLENAME,
    STARTDATE,
    ENDDATE,
    LOADSTARTTIME,
    LOADENDTIME,
    TOTALRECORDS,
    RECORDSINSERTED,
    RECORDSUPDATED,
    RECORDSDELETED,
    STATUS,
    ERROR,
    LOADEDBY
FROM lcf.AUDITLOG_OLD order by LOADSTARTTIME;

DELETE from lcf.auditlog WHERE LOADSTARTTIME<='2025-10-27 16:51:15.833'

Select * from lcf.auditlog order by LOADSTARTTIME desc;


CREATE OR REPLACE TABLE lcf.AUDITLOG (
    AUDITLOGID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 ORDER PRIMARY KEY,
    TABLENAME VARCHAR(256),
    STARTDATE TIMESTAMP_NTZ(9),
    ENDDATE TIMESTAMP_NTZ(9),
    LOADSTARTTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    LOADENDTIME TIMESTAMP_NTZ(9),
    TOTALRECORDS NUMBER(38,0),
    RECORDSINSERTED NUMBER(38,0),
    RECORDSUPDATED NUMBER(38,0),
    RECORDSDELETED NUMBER(38,0),
    STATUS VARCHAR(50),
    ERROR VARCHAR(2000),
    LOADEDBY VARCHAR(256) DEFAULT CURRENT_USER()
);

select * from lcf.auditlog order by loadstarttime desc

SELECT CURRENT_ROLE();




------------
CREATE OR REPLACE drop TABLE Jaffle_Shop.LCF.STG_DBT_RAW_JSON (
    RAW_JSON VARIANT
);

SELECT NODE_ID, NAME, TAGS
FROM Jaffle_Shop.LCF.STG_DBT_ARTIFACTS;








