CREATE SCHEMA TESTING

create or replace TABLE TESTING.TEST_METADATA_TABLE (
	SCHEMA_NAME VARCHAR(16777216),
	TABLE_NAME VARCHAR(16777216),
	COLUMN_NAME VARCHAR(16777216),
	TEST_TYPE VARCHAR(16777216),
	TEST_CONFIG VARCHAR(16777216)
);

INSERT INTO TESTING.TEST_METADATA_TABLE (
    SCHEMA_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    TEST_TYPE,
    TEST_CONFIG
)
VALUES (
    'STG',
    'stg_country',
    NULL,
    'source_to_target_range',
    '{
        "source_table": "RAW.COUNTRY",
        "source_key_list": ["COUNTRY_ID", "CITY_ID"],
        "source_timestamp": "lastupdateddate",
        "auditlog_table": "lcf.auditlog",
        "target_key": "country_city_key"
    }'
);


CREATE SCHEMA lcf

create or replace TABLE lcf.auditlog (
	AUDITLOGID NUMBER(38,0) NOT NULL,
	TABLENAME VARCHAR(256),
	STARTDATE TIMESTAMP_NTZ(9),
	ENDDATE TIMESTAMP_NTZ(9),
	LOADSTARTTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LOADENDTIME TIMESTAMP_NTZ(9),
	TOTALRECORDS NUMBER(38,0),
	RECORDSINSERTED NUMBER(38,0),
	RECORDSUPDATED NUMBER(38,0),
	RECORDSDELETED NUMBER(38,0),
	STATUS VARCHAR(50),
	ERROR VARCHAR(2000),
	LOADEDBY VARCHAR(256) DEFAULT CURRENT_USER(),
	primary key (AUDITLOGID)
);

SELECT * FROM lcf.highwatermark

create or replace TABLE lcf.highwatermark (
	TABLE_NAME VARCHAR(16777216),
	START_DATE TIMESTAMP_NTZ(9),
	END_DATE TIMESTAMP_NTZ(9)
);
