jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DATATESTER
      database: JAFFLE_SHOP
      schema: TEST
      warehouse: TASTY_BYTES_DBT_WH #JAFFLE_WH # updated to new warehouse on 07-10-2025 #TASTY_BYTES_DBT_WH
      
